### PR TITLE
Support for virtual filesystems

### PR DESCRIPTION
**Pull request by zet4**
I needed to add support for virtual filesystems (ex. implementing net/http.FileSystem interface) for a project I am working on which then compiles to a single standalone binary without any external resources so I am opening this PR to get suggestions what to improve and eventually merge it into master.

### CODE REVIEW

**Comment by tiramiseb** [comment]
I need this and I'm glad you submitted this PR. I have started working with go-bindata, using assets as args to `Parse()`, however I would need to use `extends`, which seem to be possible with this PR.

I understand this PR would allow doing it with `go-bindata-assetfs`. If I'm right, I have no particular suggestions : it would do precisely what I need.

Is it still a WIP or have you finished/tested it completely (your last commit was months ago) ?
By the way, maybe an example in the README would be useful.

**Comment by tiramiseb** [comment]
FYI, I'm successfully using it with `go.rice`:

It should work with :
```
var (
    riceBox = rice.MustFindBox("assets")
    amberOptions = amber.Options{PrettyPrint: true, LineNumbers: true, VirtualFilesystem: riceBox.HTTPBox()}
)
amber.CompileFile("filename.amber", amberOptions)
```

**Comment by zet4** [comment]
`go.rice` support was the original intent in this fork yes, I haven't really worked with amber after I was done with the project for which this was made, but yeah I would consider it finished it unless you found any issues along the way

**Comment by tiramiseb** [comment]
No issue, everythink is working, even imports and inheritance...

Maybe you could include a piece of doc with your MR, at least reusing the short example I gave above.

**Comment by zet4** [comment]
@eknkc could you please look into merging this

**Pull request merged**
